export const projectsData = [
    {
      id: 1,
      title: "SR Movie",
      image: "/images/projects/1.png",
      tag: ["All", "Web","Mobile"],
      gitUrl: "https://github.com/Satyam750/sr_movie",
      previewUrl: "https://sr-movie.vercel.app/",
    },
    {
      id: 2,
      title: "Hoo Bank",
      image: "/images/projects/2.png",
      tag: ["All", "Web","Mobile"],
      gitUrl: "https://github.com/Satyam750/hoo_bank",
      previewUrl: "https://hoo-bank-pearl.vercel.app/",
    },
    {
      id: 3,
      title: "Crypto Dashboard",
      image: "/images/projects/3.png",
      tag: ["All", "Web"],
      gitUrl: "https://github.com/Satyam750/crypto_dashboard_react",
      previewUrl: "https://crypto-dashboard-react-alpha.vercel.app/",
    },
    {
      id: 4,
      title: "Nike Page",
      image: "/images/projects/4.png",
      tag: ["All", "Web"],
      gitUrl: "https://github.com/Satyam750/nike_home_page_react",
      previewUrl: "https://nike-home-page-react.vercel.app/",
    },
    {
      id: 5,
      title: "Blog",
      image: "/images/projects/5.png",
      tag: ["All", "Web"],
      gitUrl: "https://github.com/Satyam750/Blog_react",
      previewUrl: "https://blog-react-eight-weld.vercel.app/",
    },
    {
      id: 6,
      title: "Car Showcase",
      image: "/images/projects/6.png",
      tag: ["All", "Web","Mobile"],
      gitUrl: "https://github.com/Satyam750/car_show",
      previewUrl: "https://car-show-case-snowy.vercel.app/",
    },
    {
      id: 7,
      title: "Metaverse",
      image: "/images/projects/7.png",
      tag: ["All", "Web","Mobile"],
      gitUrl: "https://github.com/Satyam750/metaverse",
      previewUrl: "https://metaverse-green-mu.vercel.app/",
    },
    {
      id: 8,
      title: "E-Commerce and Service",
      image: "/images/projects/8.png",
      tag: ["All", "Web","Mobile"],
      gitUrl: "https://github.com/Satyam750/Bizconnect_hub_b2b",
      previewUrl: "https://bizconnect-hub-b2b.vercel.app/",
    },
    {
      id: 9,
      title: "Crypto Market",
      image: "/images/projects/9.png",
      tag: ["All", "Web","Mobile"],
      gitUrl: "https://github.com/Satyam750/crypto_mad",
      previewUrl: "https://crypto-mad-ten.vercel.app/",
    },
    {
      id: 10,
      title: "Promptopia",
      image: "/images/projects/10.png",
      tag: ["All", "Web"],
      gitUrl: "https://github.com/Satyam750/Promptopia",
      previewUrl: "https://promptopia-nine-blue.vercel.app/",
    },
    {
      id: 11,
      title: "Youtube Clone",
      image: "/images/projects/11.png",
      tag: ["All", "Web","Mobile"],
      gitUrl: "https://github.com/Satyam750/Youtube_clone",
      previewUrl: "https://youtube-clone-livid-ten.vercel.app/",
    },
    {
      id: 12,
      title: "Social Media",
      image: "/images/projects/12.png",
      tag: ["All", "Web"],
      gitUrl: "https://github.com/Satyam750/sr_social_react",
      previewUrl: "https://sr-social-react.vercel.app/",
    },

  ];
